version: '3.8'

services:
  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-password}
    networks:
      - pdfspark-network

  redis:
    image: redis:latest
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - pdfspark-network

  api:
    build:
      context: ./packages/services/api
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - PORT=8000
      - MONGO_URI=mongodb://${MONGO_USERNAME:-admin}:${MONGO_PASSWORD:-password}@mongodb:27017/pdfspark?authSource=admin
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET:-development_jwt_secret_key}
      - FILE_ENCRYPTION_SECRET=${FILE_ENCRYPTION_SECRET:-development_file_encryption_key}
      - UPLOAD_DIR=/app/uploads
      - ALLOWED_ORIGINS=http://localhost:3000,https://pdfspark.app
    volumes:
      - api_uploads:/app/uploads
      - api_output:/app/output
    depends_on:
      - mongodb
      - redis
    networks:
      - pdfspark-network

  conversion-service:
    build:
      context: ./packages/conversion-service
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
      - PORT=5001
      - MONGO_URI=mongodb://${MONGO_USERNAME:-admin}:${MONGO_PASSWORD:-password}@mongodb:27017/pdfspark?authSource=admin
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=${JWT_SECRET:-development_jwt_secret_key}
      - FILE_ENCRYPTION_SECRET=${FILE_ENCRYPTION_SECRET:-development_file_encryption_key}
      - UPLOADS_DIR=/app/uploads
      - OUTPUTS_DIR=/app/outputs
      - API_URL=http://api:8000
    volumes:
      - conversion_uploads:/app/uploads
      - conversion_outputs:/app/outputs
    depends_on:
      - mongodb
      - redis
      - api
    networks:
      - pdfspark-network

  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
    networks:
      - pdfspark-network
    depends_on:
      - api

networks:
  pdfspark-network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data:
  api_uploads:
  api_output:
  conversion_uploads:
  conversion_outputs: