blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/your-org/conversion-microservices/discussions
    about: Please ask and answer questions here
  - name: Documentation
    url: https://github.com/your-org/conversion-microservices/tree/main/docs
    about: Check the documentation for usage information